name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-0d5ad758e08fc5ddbd2069f068093c4a94347d1c

      - name: Install and run soldeer
        run: |
          cargo install soldeer
          soldeer install

      - name: Run tests
        run: |
          forge test -vv
        env:
          FOUNDRY_PROFILE: fork
          FORK: true
          RPC_BASE: ${{ secrets.BASE_RPC_URL }}
          RPC_POLYGON: ${{ secrets.POLYGON_RPC_URL }}
          RPC_OPTIMISM: ${{ secrets.OPTIMISM_RPC_URL }}
          RPC_MAINNET: ${{ secrets.MAINNET_RPC_URL }}
          RPC_ARBITRUM: ${{ secrets.ARBITRUM_RPC_URL }}
