name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: fork

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-0d5ad758e08fc5ddbd2069f068093c4a94347d1c

      - name: Show Forge version
        run: |
          forge --version

      - name: Install and run soldeer
        run: |
          cargo install soldeer
          soldeer install
        id: soldeer

      - name: Run Forge build
        run: |
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          export FOUNDRY_PROFILE=fork
          export FORK=true
          forge test -vvv
        env:
          RPC_POLYGON: ${{ secrets.POLYGON_RPC_URL }}
          RPC_BASE: ${{ secrets.BASE_RPC_URL }}
        id: test
